#+TITLE:     フリーエージェント社会の到来
#+AUTHOR:    Matsumura Shigeaki
#+EMAIL:     matsu911@gmail.com
#+DATE:      2012-04-30 Mon
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  ja
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: http://matsu911.github.com
#+XSLT:
#+STYLE: <link rel="stylesheet" type="text/css" href="main.css" />

#+INCLUDE: "head.org"

* 組織人間の時代の終わり
** ポイント
20世紀後半、アメリカの社会と経済を理解するカギは、「オーガニゼーション・マン」だった。
それに対して、21世紀前半のアメリカを象徴する人物像は、フリーエージェント、すなわち、決められたひとりの上司の下で働くのではなく、大きな組織のくびきを離れて、複数の顧客を相手に、自分にとって望ましい条件で独立して働く人たちである。
フリーエージェントの台頭により、アメリカ人の仕事や人生、ビジネスに関する基本原則が揺さぶられている。
企業のあり方に始まって、医療保険、退職、教育制度、そして私たちの価値信条にいたるまで、様々なものがいま変貌している。
ニューエコノミーを本当に理解するためには、まずフリーエージエントを理解する必要がある。
** 現実
アメリカ最大の民間の雇用主は、デトロイトのゼネラル・モーターズ(GM)やフォードでもなければ、マイクロソフトでも、アマゾン・ドット・コムでもない。
人材派遣会社のマンパワー社だ。
** キーセンテンス
この本のテーマは、フリーエージェントである。
この言葉が曖昧に感じられたとしても、私はこれ以外に、この本で取り上げようとしている人たちを表現する言葉を思いつかない。
大きな組織に縛られることなく、自分の未来を自らの手で切り開くフリーエージェントたちは、アメリカの労働者の新しいモデルになりはじめている。
自由気ままな独立した労働者が経済の新しいシンボルになりつつある。
** キーワード
*** テーラーメード主義
フリーエージェントの人たちの仕事に対する姿勢。大量生産体制を整えるためにフレデリック・ウィンスロー・テイラーが提唱した画一的な「科学的管理法」、テイラー主義、に代わる概念である。
テイラーメード主義の下では、人々は従来の画一的な価値観やルール、システムに縛られることなく、自分のニーズや希望に応じて仕事の仕方を決める。
オーガニゼーション・マンの時代に全員が同じ「共通サイズの服」を着ていたのに対し、フリーエージェントは「自分サイズの服」を着るのだ。
* 3300万人のフリーエージェントたち
** ポイント
近年、労働のあり方は急速に大きな変化を遂げており、従来の統計の取り方では不十分、ないしは不的確になってきている。
(アメリカはいまだにすべての働く人たちを「農業部門」ひ「非農業部門」の2つに分類している)
フリーエージェントの特徴のひとつは、多種多様なこと。
それをグループ分けすることは簡単ではないが、それでも3つの「人種」に大きく分けることができる。
フリーランスと臨時社員とミニ起業家である。
政府の統計や民間の調査、学術的な研究をもとに考えると、控えめに見て、フリーランスは1650万人、臨時社員は350万人、ミニ起業家は1300万人と推定できる。
合計すると、アメリカには3300万人のフリーエージェントがいる計算になる。
この数字はアメリカの労働人口のほぼ4人に1人にあたる。
(ここには、在宅勤務の会社員や勤め先を頻繁に変える人など、いわば疑似フリーエージェントは含まない)
この3300万人という控えめな数字で考えても、フリーエージェント人口は、製造業の就労者や公務員の数を軽く上回る。
** 現実
カリフォルニ州で働く人の3人に2人は、アメリカのほぼすべての法律や税制度の前提となっている雇用という労働形態を取っていない。
** キーセンテンス
フリーエージェントの人たち、ひいては労働者全般は、「雇用主」と「被雇用者」にきれいに線引きできなくなってきている。
フリーエージェントは雇用主でも被雇用者でもない。
と言うより、雇用主でもあり、被雇用者でもあるのだ。
禅問答のように聞こえるかもしれないが、これがニューエコノミーの重要な特徴なのだ。
** キーワード
*** ナノコープ
「拡大を目指さない」という方針を容赦ないまでに追求している超ミニ企業。
小規模のままでいることは、オーナーの個人的な志向でもあり、競争力を得るための戦略でもある。
* デジタルマルクス主義の登場
** ポイント
フリーエージェントという働き方が登場した背景には、4つの重要な変化があった。
1 従来の労使間の社会契約、すなわち従業員が忠誠心と引き換えに会社から安定を保障してもらうという関係が崩壊した。
2 生産手段(富を生み出すのに必要な道具)が小型で安価になって個人で所有できるようになり、操作も簡単になった。
3 繁栄が社会の広い層に行き渡り、しかも長期間続いている結果、生活の糧を稼ぐことだけが仕事の目的ではなくなり、人々は仕事にやりがいを求めるようになった。
4 組織の寿命が短かくなり、人々は勤め先の組織より長く生きるようになった。
** 現実
いまやアメリカの人口の85%は、大恐慌の時代には生まれていなかった人たちで占められている。
経済的な困窮の記憶をもたない人が社会の大勢を占めるようになったのだ。
** キーセンテンス
ネットスケープが誕生したのは、1994年。翌95年には株式公開を果たした。
しかし99年には、もうこの世から消えてなくなっていた。
大手インターネット接続業者のアメリカ・オンライン(AOL)に吸収合併されたのだ。
この会社の寿命はたったの4年だった。
** キーワード
*** デジタルマルクス主義
コンピュータが安価になり、携帯型の端末が普及し、どこにいても地球規模のネットワークに接続できるようになったおかげで、労働者は再び生産手段を手にすることができるようになった。
* 新しい労働倫理
** ポイント
フリーエージェントにとって重要なのは、安定より自由。
自己表現が自己否定に取って代わった。
人々は組織の陰に身を隠すのではなく、自分の仕事に責任をもつようになった。
なにをもって成功と考えるかは、あらかじめ決められた定義に従うのではなく、自分自身で決める。
フリーエージェントにとっては、「大きいことはいいこと」ではない。
こうしてフリーエージェントは、プロテスタントの堅苦しい労働倫理を様変わりさせ、新しい労働倫理を生み出した。
フリーエージェントの労働倫理を構成するのは、「自由」「自分らしさ」「責任」「自分なりの成功」の4つの要素である。
** 現実
アメリカのフリーランスやミニ起業家1000人を対象とした99年のルー・ハリス社の調査を見ても、彼らが組織に雇われずに働くことを決めた最大の動機は、金ではない。
回答者の9割は、「自分の優先順位に従って、他人の指図を受けずに行動したい」というのを最大の動機としてあげている。
** キーセンテンス
パフ・ダディの言葉よりも、ボブ・ディランの言っていることのほうが正しいようだ。
「成功したと言えるのは、朝起きて、自分のやりたいことをやれる人だ」と、ディランは歌っている。
** キーワード
*** ピーターアウトの法則
ピーターの法則とは、階層社会の構成員は自分の能力を超えた地位まで昇進するという法則だった。
しかしいまは、ピーターアウト(次第になくなる)の法則の時代。
出世するにつれて、だんだん仕事が楽しくなくなり、やがて優秀な人材は会社を出ていってしまう。
* 仕事のポートフォリオと分散投資
** ポイント
従来の労使関係では、組織が個人に保障を与え、その代わりに個人は組織に忠誠を誓った。
しかし誰もが知っているように、この関係は崩れ去った。
転職や技術確信、企業の盛衰の速度が加速したことを受けて、フリーエージェントたちはリスクの増大に対する防衛策を取りはじめた。
投資先を分散させて資産を守るのと同じように、仕事を分散させることによって安全の保障を得ようとしはじめたのだ。
具体的には、自分の人的な資源をひとつの会社にすべてつぎ込むのではなく、複数の顧客やプロジェクトに投資する。
保障だけでなく、忠誠心も様変りした。
上司や組織に対するタテの忠誠心に代わって、ヨコの忠誠心が生まれた。
こうして、フリーエージェントは、機会(金、学習の機会、人脈)と引き換えに、能力(商品、サービス、アドバイス)を提供するようになった。
** 現実
1983年には、株式をもっている家庭の割合は5世帯に1世帯の割合だった。
しかしいまやアメリカの家庭の過半数は株式を保有している。
2000年には、アメリカの歴史上はじめて、株式を保有する人の数が大頭領選に投票した人の数を上回った。
** キーセンテンス
自由は、かつては安定を得るうえでは回り道だったが、いまは安全を得るための近道になったのだ。
** キーワード
*** ヨコの忠誠心
上司や組織に対するタテの忠誠心に代わって登場した。
タテの忠誠心と違って、ヨコの忠誠心はたいてい双方向的なものだ。
忠誠の対象は、チームや同僚、下の同僚、顧客、業界や職業、家族や友人である。
* 仕事と時間の曖昧な関係
** ポイント
フリーエージェントは、仕事と時間の関係を様変わりさせつつある。
午前9時から午後5時までの8時間労働は、臨機応変な労働時間に取って変わられた。
フリーエージェントは、従来型の会社員などと同じように週40時間程度働いていても、その40時間をそれぞれの志向に合わせて分配している。
平日と週末の区別が曖昧になっている場合も多い。
1年間の単位で見た場合も、フリーエージェントは、50時間働いて2週間休むという既存のシステムを否定し、それぞれの必要な欲求に合わせたスケジュールで働きはじめている。
フリーエージェントという働き方のメリットは、上司にスケジュールを管理されるのではなく、自分で時間を管理できることになる。
ただし、仕事とプライベートの境界線がはっきりしないし、規則正しい生活を送りにくいというデメリットがある。
** 現実
アメリカ人の平均労働時間は、ヨーロッパ人より年に350時間多い。
「過労死」という言葉をもつ日本人と比べても70時間多い。
** キーセンテンス
工場のホイッスルが1日の始まりと終わりを告げた時代と違って、仕事とプライベートの境界線はすっかり曖昧になった。
夜10時に自宅の書斎で顧客の電子メールに返事を書くような場合、どの時点で仕事が終って、プライベートな時間が始まるのか？
時間に対する不満を生んでいるのは、このように仕事とプライベートの区別がつきにくい状況なのかもしれない。
** キーワード
*** ニューエコノミーのセブンイレブン
フリーエージェントは、完全に「オフ(仕事時間外)」の状態になることはほとんどない。
24時間営業のコンビニエンスストアと同じように、客がいなくても店が空っぽのときも、店を閉めることはないのだ。
* 人と人の新しい結びつき
** ポイント
フリーエージェントたちは、ひたすら孤独に耐えるのではなく、様々な小規模のグループをつくっている。
フリーエージェント・ネーション・クラブ(FANクラブ)は、会員がときどき集まって、お互いにビジネス上のアドバイスをしたり、助け合ったりするグループだ。
フリーエージェント連合は、フリーエージェントが一緒に仕事をする非公式なチーム。
起業家ネットワークは、ミニ起業家が会費を支払って参加するブレインストーミングのための集まり。
同窓会グループは、同じ会社の「卒業生」がつくるグループだ。
こうしたグループの大半は、会員が自発的に組織した草の根のグループであるため、あまり注目されてこなかった。
しかし、このような小規模なグループの存在は、アメリカでコミュニティーが崩壊しており、フリーエージェントがその傾向を加速しているという主張に疑問を呈するものだ。
コミュニティーは死んだわけではない。
コミュニティーの性格が変わっただけだ。
** 現実
フリーエージェントが自発的につくるグループの先駆け的存在は、1927年にベンジャミン・フランクリンがつくった「ジャントー」というグループだ。
ジャントーが創設した会員制の貸し出し図書館は、アメリカ初の公共図書館に発展していった。
** キーセンテンス
FANクラブは、企業の取締役会のおうな一面がある一方で、心理療法のグループ療法のような一面もある。
顧客探しの場であると同時に、生きがい探しの場でもある。
こうしたグループは、私利私欲によって生まれ、メンバーの信頼に支えられて存続する。
** キーワード
*** フリーエージェント連合
フリーエージェントが協力して仕事をするチーム。
法律事務所や会計事務所などのパートナーシップと呼ばれる形態と似ているが、メンバー同士の関係はもっと流動的で、組織や運営の決まり事は契約ではなく、明文化されていない約束によって決められている。
* 互恵的な利他主義
** ポイント
フリーエージェントの世界には、これまでの企業の組織図とは似ても似つかない独特の「組織図」がある。
ここでは、人と人との関係はタテの関係ではなく、ヨコの関係だ。
個人がどの程度の力をもつかは、あらかじめ決められている地位や肩書きによってではなく、人間関係によって決まる。
フリーエージェントの人間関係は、緊密で固定的でお仕着せものではなく、緩やかで流動的でえり好みできることが特徴だ。
フリーエージェントという働き方が円滑に機能する土台になっているのは、賢い利己心、すなわち「あなたがいつか力になってくれると思うから、いまあなたの力になろう」という発想である。
自由気ままで、一見すると裏切りが横行していそうなイメージとは裏腹に、フリーエージェント経済は、実は人々に道徳的な振舞いを促す。
フリーエージェント経済をまとめているのは、様々な宗教で教える黄金律、「汝の欲するところを他人になせ」という考え方なのだ。
** 現実
社会学者のマーク・グラノヴェターの研究によると、どうやっていまの仕事に就いたのかという質問に対して、大半の人は「知り合い」を介して仕事を見つけたと答えた。
そう答えた人のほぼ6人中5人は、とくに親しい関係にあるわけではない人に仕事を紹介してもらっていた。
ろくに知らない人に仕事を紹介してもらったという人もいた。
** キーセンテンス
フリーエージェントの組織図は流動的なものだ。
流動的なものだから、ピラミッド型の構造になることもほとんどない。
あるプロジェクトでは同格のスタップだった人間が、別のプロジェクトではボスになることもある。
いまの仕事の下請け業者が明日には依頼主になるかもしれない。
フリーエージェントの組織図は、従来の企業の組織図よりも、むしろ人間の脳に似ている。
私たちの脳の中では、古いニューロンと新しいニューロンが絶えず結びつき、離れてはまた結びついて、新しい回路をつくっている。
私たちはこうして、ものを考え、ものを学び、ものを記憶するのだ。
従来の20世紀型の雇用形態に比べて、フリーエージェントという働き方のほうが人間の性質に調和しているのは、もしかするとこのためかもしれない。
** キーワード
*** フリーエージェントのOS
コンピュータのOSのウィンドウズやDOSやリナックスと同じように、フリーエージェントのOSは、フリーエージェント経済が機能する土台となっている。
その基本的な構成要素は、信頼である。
この信頼は、互恵的な利他主義という形を取る。
* オフィスに代わる「第3の場所」
** ポイント
フリーエージェントという働き方の土台となる経済的なインフラストラクチャーが生まれている。
コピー店、コーヒーショップ、書店、エグゼクティブスイート、インターネット、大型オフィス用品店、私書箱センター、宅配便の翌日配送サービスで構成されるこの新しいインフラは、2つの特徴がある。
第一は、中央計画的なものではなく、自発的に形成されていること。
第二は、フリーエージェントたちが集まることのできる「第三の場所」をつくり出していることだ。
** 現実
2002年に全米の在宅オフィスがインターネット接続に費やす金額は、102億ドル以上になる。
** キーセンテンス
スターバックスに行けば、値段はちょっと高くても、おいしいコーヒーが飲めるということは、誰でも知っている。
けれど、ほとんどの人が気づいていないのは、スターバックスは消費者向け飲料ビジネスの企業ではないということだ。
実態を見れば、事業用不動産ビジネスの会社と言ったほうがいい。
私をはじめ大勢のフリーエージェントにとって、コーヒーショップはオフィスとして機能しているからだ。
** キーワード
*** フリーエージェントのインフラストラクチャー
フリーエージェント経済が機能する物理的な土台。
民間の手で、自発的に組織されている。
* 仲介者、エージェント、コーチ
** ポイント
フリーエージェント経済は、オーガニゼーション・マンの経済とは2つの点で根本的に異なる。
第一に、力の所在が組織から個人に移った結果、資本ではなく人材が最も重要な資源になった。
そして、この重要な資源の価格を決定し、分配するための新しい市場が生まれた。
第二に、仕事は、個人の感情と無縁の退屈なものではなく、働く人の心に負担を強いるものになった。
この2つの要因に後押しされて、フリーエージェント・ネーションが機能するのを助ける新しい専門職が登場した。
臨時社員派遣会社から発展した人材仲介ビジネスは、フリーエージェントの人材を求める買い手と、仕事を求めるフリーエージェントの橋渡し役を努めることにより、新しい人材市場が効率的に機能するのを助けている。
エージェントは、これまでの俳優や作家、スポーツ選手のエージェントと同じように、経済面の役割と心理面の役割の両方を果たしている。
エージェントは、フリーエージェントの代理人として仕事の条件を交渉するだけでなく、プライベートな問題についても相談に乗る。
コーチは、人材仲介業者やエージェントより、働く人の心に密着した機能を果している。
仕事や人生についての根本的な問題について相談に乗る。
コーチは、キャリアカウンセラーと教会の司祭を合わせたような存在だ。
** 現実
ある調査によると、アメリカでは、年収7万5000ドル以上の人の5%は、仕事の条件の交渉をエージェントに任せているという。
** キーセンテンス
コーチは、診察椅子をもたない精神科医であり、フローチャートをもたない経営コンサルタントであり、ショットグラスをもたない聞き上手なバーテンダーでもある。
** キーワード
*** 会社版「お節介おばさん」
短期的に人材を必要としている企業に、フリーエージェントを引き合せるビジネス。
* 「自分サイズ」のライフスタイル
** ポイント
工業経済の時代が訪れ、それまで一体だった仕事と家庭が切り離された。
フリーエージェント経済は、それを再び統合しようとしている。
フリーエージェントたちは、仕事と家庭のバランスを取ろうとする、仕事と家庭を二者択一ととらえる発想と言ってもいい、のではなく、仕事と家庭をブレンドしている。
企業の「家庭に優しい」制度や法律で定められた家族休暇の制度がうまく機能していないのは、ひとつにはこのためだ。
こうした制度は、人々に仕事と家庭をブレンドするのではなく、バランスを取ることを強いるものであり、「自分サイズの服」を求める人たちに「共通サイズの服」を着せるものと言えるからだ。
こうした状況で、フリーエージェントたちは、政府や企業に頼るのをやめて、もっと人間の性質と進化の過程に沿っていると思われる働き方を選びはじめた。
** 現実
中小の家族経営の企業は、全世界の働き口の約6割を生み出している。
** キーセンテンス
フリーエージェントのカップルという形態は、いまになって生まれたものではない。
工業経済の時代になるまでは、夫婦はたいてい一緒に働いていた。
インターネットの登場により、そうした夫婦の商売は必ずしも零細ビジネスとは限らなくなった。
** キーワード
*** 通勤夫婦
夫婦ともに会社などに勤務し、子供をもっている夫婦によく見られる状態。
毎朝、慌ただしく子供を託児所や学校に送り届け、勤務先に出勤し、夕方はその逆の順番で慌しく家に帰る。
毎日がその繰り返しで過ぎていく。
* 古い制度と現実のギャップ
** ポイント
アメリカの法制度の多くは、大半の人が単一の雇用主の下でフルタイムの恒久的な職に就いている状態を前提にしている。
こうした法律は耐用年数を過ぎて生き延びており、主に3つの面でフリーエージェント経済の足を引っ張っている。
医療保険、税制、地域地区規制の3つの分野である。
雇用主をもたないで働く人が増えたいま、雇用主を通じて加入する従来の医療保険制度は時代遅れになっている。
この制度は歴史的な偶然から生れたものであり、経済的・倫理的な必然性はほとんどない。
しかもこの制度のおかげで、無保険者のフリーエージェントが大勢いるうえに、医療保険を失うことを恐れて独立に踏み切れない人も多い。
一方、現在のアメリカの税制は3つの点でフリーエージェントに不利な内容になっている。
フリーエージェントは、社会保障税を給与所得者の2倍支払わされるのに加えて、医療保険料の全額控除を認められず、頭が痛くなるほど複雑な税制のおかげで時間とコストと精神的ゆとりを奪われている。
自治体の地域地区規制は、仕事と家庭の明確な区別を前提にしており、その多くは在宅のフリーエージェントに厳しい規制を課している。
自宅でビジネスを営むことを禁止している自治体もある。
** 現実
スタンフォード大学のある研究者の試算によると、税制が複雑なおかげで、徴税費用で1000億ドル以上、脱税で1000億ドル、「人々が税制上有利な投資をしようとすることによる歪み」により1000億ドルの税収が失われているという。
** キーセンテンス
いま雇用主を通じて医療保険の適用を受けているアメリカ人は、幸せを噛みしめたほうがいい。
そもそもは、現在のような制度になるはずではなかったのだ。
** キーワード
*** コブラ・ベビー
勤務先を退職したフリーエージェントが退職後18ヶ月以内につくった子供。
アメリカでは、「包括財政調整法(略称COBRA)」という法律によって、雇用主は、退職した従業員が自費で医療保険料を支払い続ける場合は、退職後18ヶ月間は医療保険を提供し続けなければならないことになっている。
フリーエージェントのなかには、この制度を利用して子供をつくる人が少なくない。
* 万年臨時社員と新しい労働運動
** ポイント
言うまでもなく、フリーエージェントにもマイナスの面はある。
劣悪な環境で、雀の涙ほどの給料のために退屈な仕事をしている臨時社員もいる。
正社員と同じ仕事をしているのに、派遣会社から派遣された臨時社員であるという理由で、医療保険などの付加給付を与えられない人たちもいる。
これは確かに嘆かわしいことだが、こうした状況に置かれている人は臨時社員のごく一部であり、臨時社員はフリーエージェントのごく一部に過ぎない。
それに、今日の労働の現場で不平等を生み出しているのは、その人が正社員であるか臨時社員であるかではなく、需要のある技能をもっているかいないか、新しい労働市場における交渉力をもっているかいないかの違いなのだ。
将来は、いまのプロスポーツのようなシステムが一般的になるかもしれない。
フリーエージェントたちは労働組合に加入し、組合を通じて最低報酬を保証される一方で、多くは個人代理人(エージェント)に依頼して交渉に当たらせて、もっといい条件で契約を結ぼうとするようになるだろう。
** 現実
アフリカ系は、アメリカの労働人口の11%を占めるに過ぎないのに、臨時社員人口の22%を占めている。
** キーセンテンス
テンプ・スレーブは、マズローの「欲求のピラミッド」を登ることはないし、FANクラブの会合で映画「ザ・エージェント」の意味を話し合ったりもしない。
そんなのとは無縁の生活だ。
この人たちは、アメリカの労働者のなかでも最も不満を抱いている人たちと言ってもいい。
** キーワード
*** 万年臨時社員
正社員と机を並べて、同じ仕事をしているのに、臨時社員という扱いであるために、医療保険や年金、ストックオプションなどを与えられていない人たち。
* リタイヤからeリタイヤへ
** ポイント
フリーエージェントの未来では、引退(リタイヤ)する人は少くなる。
代わりに、「eリタイヤ」する人が増えるだろう。
65歳で完全に仕事をやまてしまうのではなく、フリーエージェントとして働き続けるようになる。
インターネットを使って仕事を探し、働くのだ。
人口構成の変化を見れば、eリタイヤは、需要と供給の関係が生み出す必然の現象と言える。
ベビーブーム世代が高齢になれば、健康で、技術を備え、テクノロジーに通じ、自己実現を目指す高齢者が大勢登場することになる。
このように高齢の労働力の供給が増える一方で、労働力人口は減少に向かっており、そうした高齢の労働力に対する需要が一気に高まることが予想される。
** 現実
フランクリン・ルーズベルト大頭領が社会保障法を成立させて、標準的な引退年齢を65歳に定めた当時、アメリカ人の平均寿命は63歳だった。
しかし、現在の平均寿命は76歳だ。
しかも、医学の進歩により、寿命はさらに伸びるだろう。
** キーセンテンス
ベビーブーム世代がこれから両親から相続すると見込まれている金額は、総額で10兆ドルを上回る。
もちろん、遺産は高価な美容整形や着心地のいい水着を買うためにも使われるだろう。
それでも、フリーエージェントとして再出発するための軍資金は、たっぷり残るはずだ。
** キーワード
*** eリタイヤ
人生の新しい段階。
65歳を過ぎても、これまでのように引退(リタイヤ)するのではなく、インターネットを駆使してフリーエージェントとして働くことを言う。
* テイラーメード主義の教育
** ポイント
フリーエージェントの時代には、様々な形で「脱学校」化が進む。
学校での義務教育は次第に廃れて、多様な教育の形態が生まれる。
在宅教育はますます盛んになるだろう。
仕事の場以外では、在宅教育は、フリーエージェント的な価値観が最も強くあらわれる場と言える。
それぞれの専門を活かして、在宅教育の子供たちの「先生」になるフリーエージェントも増えるだろう。
これまでのような高校は姿を消し、もっとフリーエージェント経済に適合したものに変わっていく。
子供の頃に勉強する週間を身につけた人たちは、大人になっても独力で勉強する。
その結果、大学の学位の価値が下り、非公式の自発的な学習の価値が高まる。
** 現実
現在、アメリカの大学生の40%は25歳以上だ。
いくつかの予測によれば、数年後には35歳以上の大学生の数が18歳と19歳の学生の数を上回るという。
** キーセンテンス
私たちは、従来の典型的な学校に足を踏み入れるとき、過去に足を踏み入れているのだ。
それは、フレデリック・ウィンスロー・テイラーが設計し、オーガニゼーション・マンが住む場所である。
アメリカ社会の中で、フリーエージェント経済の価値観や形態に最も適応できていない機関は、アメリカ人が最も重要だと言い続けてきた機関、すなわち学校なのだ。
** キーワード
*** 「感謝祭のターキー」型の教育
20世紀に主流だった教育モデル。
社会は、公教育というオーブンの中に子供を12年間入れて、しっかり焼けたら、企業などの雇用主に引き渡していた。
選ばれた一部は、大学という名前の場所であと4年間、最後の仕上げをされた。
* 生活空間と仕事場の穏やかな融合
** ポイント
フリーエージェントの時代には、道具倉庫としてのオフィスは姿を消し、2つの新しいタイプのオフィスが登場する。
第一は「プライベート・アイダホ」とでも呼ぶべき形態のオフィス。
すなわち、集中力を要する仕事をするための静かな個人用スペースである。
第二は「フリーエージェントの山小屋」。
仲間が顔を合わせて協力し合う場、行きつけのパブとエグゼクティブスイートを足して2で割ったような場である。
こうした新しいタイプのオフィスの登場は、住宅と事業用不動産のあり方も変容させる。
ホームオフィスが当り前になり、リフォーム産業に好景気をもたらす。
オフィスではグループで利用するスペースが増え、「トロフィータワー」は独立性の高い労働力のための多目的スペースに変わっていく。
** 現実
ウィークデーのデスクやオフィス、個人用作業スペースの利用状況を見た場合、常時その7割が空席になっているという。
週末や休日も計算に入れると、使用中のデスクの割合は15%程度に過ぎない。
** キーセンテンス
「フリーエージェントの山小屋」では、フリーエージェントたちが集まって、前の晩のテレビドラマの話題で盛り上がったり、仲間と一緒に共同のプロジェクトに取り組んだりすることができる。
この「山小屋」は、仕事場と言っても、キュービクル(個人用の間仕切りスペース)全盛の90年代のオフィスより、キンコーズやスターバックスに近い。
フリーエージェントたちは金を払って会員になり、同僚と噂話に花を咲かせたり、仕事中に誰かに話かけられるなど、いまは会社勤めの嫌な点だと思っていることをするために、こうした仕事場に出かけていくようになる。
** キーワード
*** HOHO(His Office/Her Office)
「SOHO(Small Office/Home Office)」の変形版。
カップルが自宅内にそれぞれ個人用のオフィスをもつ家庭のこと。
* 個人が株式を発行する
** ポイント
フリーエージェントの時代には、いま企業がやっているのと同じような方法で、個人も資金を調達するようになる。
個人も、融資や社債発行により借金をしたり、株式を売って金を集めはじめる。
「FAN債」や「フリーエージェント版IPO」など、新しい金融手段も続々と生まれるだろう。
** 現実
大手会計事務所アンダーセンの98年の調査によれば、起業家の47%は、個人のクレジットカードで事業の資金を調達したことがあるという。
93年に比べれて、この数字は倍増している。
小規模なビジネスの資金調達方法としては、クレジットカードは銀行の融資以上に有力な手段になっている。
** キーセンテンス
プロボクサーのなかには、投資家に株式を売って、トレーニング資金を調達している人もすでに大勢いる。
アメリカのプロボクサーの10人に1人は、こうした方法で資金を得ている。
次の戦いの準備をする資金を手にするために自由をある程度手放しても構わないと考えているのは、プロボクサーだけではないだろう。
フリーランスで働く人のなかにも、こうしたプロボクサーと同じ道を選択する人もいるかもしれない。
** キーワード
*** FAN債
フリーエージェント版の社債。
学生ローンより利用しやすいが、クレジットカードより金利は低い。
FAN債市場を活性化するためには、連邦抵当金庫(ファニー・メイ)が住宅ローンの債権を大量に買い取って、証券化して投資家に販売しているように、FAN債を買い取って証券化する仕組みが必要になるだろう。
* ジャストインタイム政治
** ポイント
フリーエージェントの時代には、ホワイトハウスへの道はホームオフィスを通るようになる。
アメリカ政治の眠れる巨人、すなわちフリーエージェントたちがいよいよ選挙で大きな影響力をもつようになる。
この新しい政治勢力は、ニューディール政策に代わって、フリーエージェント経済に合った新しい政策を生み出す原動力になるだろう。
このいわば「ニューエコノミー・ディール」は、医療保険や年金の支給、労働者の権利保護のメカニズムの中核に、企業ではなく個人を据えるものになりそうだ。
フリーエージェントたちは、税制の簡素化、福祉需給者のためのマイクロファイナンスの充実、臨時社員の権利章典の制定、個人失業勘定制度の創設などを要求していくだろう。
** 現実
ギャラップ社の世論調査によれば、大企業を国家に対する脅威であると考える人は、労働組合を脅威であると考える人の2倍にのぼる。
** キーセンテンス
大半の政治家は、斜陽の古いグループにこだわり続けて、上げ潮の若いグループを黙殺している。
たとえフリーエージェントに目を向けることがあっても、共和党は、政治に敵対的で強欲な連中という見方しかしないし、民主党は、抑圧された「臨時」労働力としてしか見ない。
** キーワード
*** ジャストインタイム政治
ジャストインタイムの生産システムの政治板。
いまの政治家に求められているのは、支持層を固めてそれを守ろうとするのではなく、目の前の政治課題に対応するための政治的連合をその都度リアルタイムで築いていくことだ。
* ビジネス、キャリア、コミュニティーの未来像
** ポイント
フリーエージェントの時代には、ビジネスやキャリアのあり方、コミュニティーの築き方も変わってくる。
経済の生態系には巨大企業とミニ企業が主に生息し、中間サイズの企業は廃れていく。
マイクロペイメントや物々交換の拡大により、個人やミニ企業の間の取引は、いまより容易になる。
いままでのような管理職は姿を消し、特定のプロジェクトのために適材適所の人材を集めることのできるプロジェクトマネジャーが生き残る。
フリーエージェントの台頭により人と人との触れ合いがなくなるという指摘は杞憂に終わる。
むしろ、地域社会やコミュニティーは活気を取り戻すだろう。
フリーエージェントの未来は、男性ではなく、女性が中心になって築いていく。
21世紀は、女性の世紀になるのかもしれない。
** 現実
1999年の統計によれば、女性が経営する企業の数は全米で910万社。
全体の38%にあたる。
一部の推計によれば、2005年には、女性が経営する会社は大小合わせれば、全体の半数を占めるようになるという。
** キーセンテンス
「規模の経済」の恩恵を受ける企業はとほうもなく巨大化し、国家の規模に近づく。
一方、企業の小規模化もさらに進行し、フリーランスやミニ企業は増え続ける。
しかし、その中間サイズの企業は消滅したり、存在感が薄まっていく。
新しい経済の生態系では、たくさんの象ともっとたくさんのネズミが活躍し、その中間の大きさの種はほろんでいくのだ。
** キーワード
*** レゴ型のキャリア
私たちのキャリアは、あらかじめ用意された梯子を一段一段、決められた方法で上っていくだけではなくなる。
選択肢はもっと多様になる。
レゴのブロックで遊ぶ子供のように、コネや技能、意欲、機会などのブロックを使って、自分なりのキャリアの積み木をつくり、やがてまた新しい積み木をつくり直していく。
組み立て方は無限にある。
